### PR TITLE
Upgraded code to Java 8 and Joda time.

### PR DESCRIPTION
**Pull request by guidomedina**
I have rebased my branch from your current master so that you don't have to resolve conflicts, tests passed but NPE at some test:
```
ERROR FixApplicationAdapter - Uncaught application exception.
io.netty.handler.codec.DecoderException: java.lang.NullPointerException
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:99)
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:283)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:187)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:32)
	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:299)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at fixio.netty.pipeline.server.ServerSessionHandler.initSession(ServerSessionHandler.java:122)
	at fixio.netty.pipeline.server.ServerSessionHandler.decode(ServerSessionHandler.java:76)
	at fixio.netty.pipeline.server.ServerSessionHandler.decode(ServerSessionHandler.java:33)
	at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89)
	... 18 more
```

### CODE REVIEW

**Comment by guidomedina** [comment]
PriceServer is not working for me, OOM.

**Comment by kpavlov** [comment]
> PriceServer is not working for me, OOM.
I'll check it

Guido I saw the similar exception in travis after merge (`review` branch), that's why I postponed with  merge to develop/master.
Could you tell what's exact wrong with Java8 JSR-310 implementation?
I think we're fine with millisecond precision since FIX protocol supports only milliseconds (http://www.fixtradingcommunity.org/FIXimate/FIXimate3.0/en/FIX.5.0SP2/fix_datatypes.html - e.g. UTCTimestamp)
The only reason to move to to JodaTime I see is to avoid type conversion if JodaTime is used everywhere in the system. For this case I think there should be support for getting/setting JSR-310 and Joda types in fix field types.

**Comment by guidomedina** [comment]
Java time at least on Debian was giving me an exception when I was trying to create a `LocalTime` with millis, basically the constructor (builder pattern like), doesn't have a parameter for millis, instead you have to pass nanos (millis converted to nanos) and when I did that the JVM complained of not supporting such operation which for me was a blocker.

**Comment by guidomedina** [comment]
The offending call was: http://docs.oracle.com/javase/8/docs/api/java/time/LocalTime.html#of-int-int-int-int-

**Comment by guidomedina** [comment]
I'll give it another try tonight and see if I can make it work, maybe was that I was missing NTP package on my Debian laptop, but such exception scared me a bit, either it is that I'm using Debian Jessie RC1 with Oracle Java 8u31 and for the time being is buggy? Honestly I have my concerns if this is a JVM bug, though I'm not sure why Java time is so much more difficult to use than Joda time when Joda time was the initial proposal.

**Comment by kpavlov** [comment]
Now there is nothing to merge

**Comment by guidomedina** [comment]
Yes, deleting branch to remove noise.

**Pull request closed without merging**
