### PR TITLE
Configurable time stamp precision

### PR DESCRIPTION
**Pull request by dmtrk**
Removed joda and switched to using java.time to support "SECONDS", "MILLIS", "MICROS", "NANOS" in time stamp fields. Added sender/target LocationID to SessionId

### CODE REVIEW

**Comment by kpavlov** [comment]
Hi @dmtrk 
Did you make any performance tests ?

**Comment by kpavlov** [comment]
I would split this PR: thare are many different changes: migraiton to java.time, defaultApplVerID, 
 add LocationID to sessionID

**Comment by dmtrk** [comment]
I,m not sure what the expectation is..


on sun jdk (Java HotSpot(TM) 64-Bit Server VM (build 25.141-b15, mixed mode)) i get :

Iteration  10: 256133.937 ops/s



on open jdk (OpenJDK 64-Bit Server VM (build 25.03-b03, mixed mode))

Iteration  10: 280480.097 ops/s


Dmitri



________________________________

**Comment by kpavlov** [comment]
@dmtrk, please compare current master with Joda & new implementation with java.time.
I expect that the performance did not get worse

**Comment by dmtrk** [comment]
ok


________________________________

**Comment by dmtrk** [comment]
just to explain where I'm coming from..


MIFID II and MiFIR regulatory reporting requirements mandate  higher resolution and greater granularity of time  stamps.

(EP206 Clock Synchronization Datatype Enhancement)


________________________________

**Pull request merged**
